AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Runs a daily report for expensive resources"
  
Resources:
  ReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambdaHandler
      Timeout: 10
      Runtime: nodejs18.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - app.tsx

Outputs:
  HelloWorldFunction:
    Description: "Report Function Lambda Function ARN"
    Value: !GetAtt ReportFunction.Arn
